kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - cd back-end
  - npm install
  - npm run test:ci

services:
- name: mongo
  image: mongo:4
  command: [ --smallfiles ]
  ports:
  - 27017
