enum ERROR_CODE {
  AUTH_FAILED = "AUTH_FAILED",
  AUTH_NOT_LOGIN = "AUTH_NOT_LOGIN",

  USERS_BAD_USERNAME = "USERS_BAD_USERNAME",
  USERS_EXIST = "USERS_EXIST",
  USERS_EASY_PASSWORD = "USERS_EXIST"
}

enum POSTS_SORT {
  TIME = "TIME",
  BBS = "BBS",
  HN = "HN"
}

export { ERROR_CODE, POSTS_SORT };
